"""Table definitions (SQLAlchemy Core). Migrations are the source of truth for the schema.

A test checks that these definitions and the migrated schema stay identical.
"""

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    false,
    true,
)

from tindeerr.storage.db import UtcDateTime

metadata = MetaData(
    naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)

#: Settings edited by the admin. Secret values are encrypted (``encrypted`` = true).
settings = Table(
    "settings",
    metadata,
    Column("name", String(64), primary_key=True),
    Column("value", Text, nullable=False),
    Column("encrypted", Boolean, nullable=False),
    Column("updated_at", UtcDateTime, nullable=False),
)

#: Exactly one row describing the instance.
server_state = Table(
    "server_state",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=False),
    Column("created_at", UtcDateTime, nullable=False),
    Column("setup_completed_at", UtcDateTime, nullable=True),
    # Random, generated by migration 0002: the Jellyfin / Emby DeviceId and the JWT iss.
    Column("install_id", Text, nullable=False),
    # SHA-256 of the setup code while first-run setup is pending.
    Column("setup_code_hash", Text, nullable=True),
    # "jellyfin:<id>", "emby:<id>" or "plex:<machineIdentifier>".
    Column("media_server_identity", Text, nullable=True),
    CheckConstraint("id = 1", name="single_row"),
)

#: People, created at their first sign-in through the media server.
users = Table(
    "users",
    metadata,
    Column("id", Text, primary_key=True),
    Column("media_server_user_id", Text, nullable=True, unique=True),
    Column("name", Text, nullable=False),
    Column("media_server_admin", Boolean, nullable=False, server_default=false()),
    Column("promoted", Boolean, nullable=False, server_default=false()),
    Column("remote_access", Boolean, nullable=False, server_default=true()),
    Column("enabled", Boolean, nullable=False, server_default=true()),
    Column("disabled_reason", Text, nullable=True),
    Column("daily_generation_limit", Integer, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    Column("last_sign_in_at", UtcDateTime, nullable=True),
    Column("last_seen_at", UtcDateTime, nullable=True),
    Column("synced_at", UtcDateTime, nullable=True),
    CheckConstraint(
        "disabled_reason IS NULL OR disabled_reason IN ('admin', 'media_server', 'unlinked')",
        name="disabled_reason",
    ),
    CheckConstraint(
        "(enabled = 1) = (disabled_reason IS NULL)",
        name="disabled_reason_matches_enabled",
    ),
)

#: One row per signed-in device or browser, plus the first-run setup session.
sessions = Table(
    "sessions",
    metadata,
    Column("id", Text, primary_key=True),
    Column("kind", Text, nullable=False),
    Column("user_id", Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=True),
    # SHA-256 of the cookie token for "web" and "setup"; null for "mobile" (JWT + refresh).
    Column("token_hash", Text, nullable=True, unique=True),
    Column("csrf_token", Text, nullable=True),
    Column("device_name", Text, nullable=True),
    Column("platform", Text, nullable=True),
    Column("app_version", Text, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    Column("last_seen_at", UtcDateTime, nullable=False),
    Column("expires_at", UtcDateTime, nullable=False),
    Column("reauth_at", UtcDateTime, nullable=True),
    Column("revoked_at", UtcDateTime, nullable=True),
    Column("revoked_reason", Text, nullable=True),
    CheckConstraint("kind IN ('mobile', 'web', 'setup')", name="kind"),
    CheckConstraint("(kind = 'setup') = (user_id IS NULL)", name="user_only_outside_setup"),
    CheckConstraint(
        "(kind = 'mobile') = (token_hash IS NULL) AND (kind = 'mobile') = (csrf_token IS NULL)",
        name="cookie_sessions_carry_a_token",
    ),
    CheckConstraint("(revoked_at IS NULL) = (revoked_reason IS NULL)", name="revoked_with_reason"),
    CheckConstraint(
        "revoked_reason IS NULL OR revoked_reason IN ('logout', 'user', 'admin', 'disabled', "
        "'reuse', 'setup_completed', 'superseded', 'server_changed')",
        name="revoked_reason",
    ),
)

#: Refresh tokens of mobile sessions. Used ones are kept, so reuse is always detected.
refresh_tokens = Table(
    "refresh_tokens",
    metadata,
    Column("token_hash", Text, primary_key=True),
    Column(
        "session_id",
        Text,
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("created_at", UtcDateTime, nullable=False),
    Column("expires_at", UtcDateTime, nullable=False),
    Column("used_at", UtcDateTime, nullable=True),
)

#: Phone pairings started from the console (the flow itself arrives with the endpoints).
pairings = Table(
    "pairings",
    metadata,
    Column("id", Text, primary_key=True),
    Column("user_id", Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("code_hash", Text, nullable=False, unique=True),
    Column("status", Text, nullable=False),
    Column("code_challenge", Text, nullable=True),
    Column("device_name", Text, nullable=True),
    Column("platform", Text, nullable=True),
    Column("app_version", Text, nullable=True),
    Column("requested_from", Text, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    Column("expires_at", UtcDateTime, nullable=False),
    Column("requested_at", UtcDateTime, nullable=True),
    Column("approved_at", UtcDateTime, nullable=True),
    Column("completed_at", UtcDateTime, nullable=True),
    Column("revoked_at", UtcDateTime, nullable=True),
    Column("session_id", Text, ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True),
    CheckConstraint(
        "status IN ('pending', 'awaiting_approval', 'approved', 'completed', 'revoked')",
        name="status",
    ),
)

#: Sessions of one user, most recent first (the console and the app list them).
Index("ix_sessions_user_id_created_at", sessions.c.user_id, sessions.c.created_at)
