"""Identifiers generated by the server: 128 random bits, base64url (docs/auth.md)."""

import secrets
from typing import Final

_ID_BYTES: Final = 16


def new_id() -> str:
    """Return a fresh 128-bit identifier, base64url without padding."""
    return secrets.token_urlsafe(_ID_BYTES)
