"""Table definitions (SQLAlchemy Core). Migrations are the source of truth for the schema.

A test checks that these definitions and the migrated schema stay identical.
"""

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    false,
    true,
)

from tindarr.storage.db import UtcDateTime

metadata = MetaData(
    naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)

#: Settings edited by the admin. Secret values are encrypted (``encrypted`` = true).
settings = Table(
    "settings",
    metadata,
    Column("name", String(64), primary_key=True),
    Column("value", Text, nullable=False),
    Column("encrypted", Boolean, nullable=False),
    Column("updated_at", UtcDateTime, nullable=False),
)

#: Exactly one row describing the instance.
server_state = Table(
    "server_state",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=False),
    Column("created_at", UtcDateTime, nullable=False),
    Column("setup_completed_at", UtcDateTime, nullable=True),
    # Random, generated by migration 0002: the Jellyfin / Emby DeviceId and the JWT iss.
    Column("install_id", Text, nullable=False),
    # SHA-256 of the setup code while first-run setup is pending.
    Column("setup_code_hash", Text, nullable=True),
    # "jellyfin:<id>", "emby:<id>" or "plex:<machineIdentifier>".
    Column("media_server_identity", Text, nullable=True),
    CheckConstraint("id = 1", name="single_row"),
)

#: People, created at their first sign-in through the media server.
users = Table(
    "users",
    metadata,
    Column("id", Text, primary_key=True),
    Column("media_server_user_id", Text, nullable=True, unique=True),
    Column("name", Text, nullable=False),
    Column("media_server_admin", Boolean, nullable=False, server_default=false()),
    Column("promoted", Boolean, nullable=False, server_default=false()),
    Column("remote_access", Boolean, nullable=False, server_default=true()),
    Column("enabled", Boolean, nullable=False, server_default=true()),
    Column("disabled_reason", Text, nullable=True),
    Column("daily_generation_limit", Integer, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    Column("last_sign_in_at", UtcDateTime, nullable=True),
    Column("last_seen_at", UtcDateTime, nullable=True),
    Column("synced_at", UtcDateTime, nullable=True),
    CheckConstraint(
        "disabled_reason IS NULL OR disabled_reason IN ('admin', 'media_server', 'unlinked')",
        name="disabled_reason",
    ),
    CheckConstraint(
        "(enabled = 1) = (disabled_reason IS NULL)",
        name="disabled_reason_matches_enabled",
    ),
)

#: One row per signed-in device or browser, plus the first-run setup session.
sessions = Table(
    "sessions",
    metadata,
    Column("id", Text, primary_key=True),
    Column("kind", Text, nullable=False),
    Column("user_id", Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=True),
    # SHA-256 of the cookie token for "web" and "setup"; null for "mobile" (JWT + refresh).
    Column("token_hash", Text, nullable=True, unique=True),
    Column("csrf_token", Text, nullable=True),
    Column("device_name", Text, nullable=True),
    Column("platform", Text, nullable=True),
    Column("app_version", Text, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    Column("last_seen_at", UtcDateTime, nullable=False),
    Column("expires_at", UtcDateTime, nullable=False),
    Column("reauth_at", UtcDateTime, nullable=True),
    Column("revoked_at", UtcDateTime, nullable=True),
    Column("revoked_reason", Text, nullable=True),
    CheckConstraint("kind IN ('mobile', 'web', 'setup')", name="kind"),
    CheckConstraint("(kind = 'setup') = (user_id IS NULL)", name="user_only_outside_setup"),
    CheckConstraint(
        "(kind = 'mobile') = (token_hash IS NULL) AND (kind = 'mobile') = (csrf_token IS NULL)",
        name="cookie_sessions_carry_a_token",
    ),
    CheckConstraint("(revoked_at IS NULL) = (revoked_reason IS NULL)", name="revoked_with_reason"),
    CheckConstraint(
        "revoked_reason IS NULL OR revoked_reason IN ('logout', 'user', 'admin', 'disabled', "
        "'reuse', 'setup_completed', 'superseded', 'server_changed')",
        name="revoked_reason",
    ),
)

#: Refresh tokens of mobile sessions. Used ones are kept, so reuse is always detected.
refresh_tokens = Table(
    "refresh_tokens",
    metadata,
    Column("token_hash", Text, primary_key=True),
    Column(
        "session_id",
        Text,
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("created_at", UtcDateTime, nullable=False),
    Column("expires_at", UtcDateTime, nullable=False),
    Column("used_at", UtcDateTime, nullable=True),
)

#: Phone pairings started from the console (the flow itself arrives with the endpoints).
pairings = Table(
    "pairings",
    metadata,
    Column("id", Text, primary_key=True),
    Column("user_id", Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("code_hash", Text, nullable=False, unique=True),
    Column("status", Text, nullable=False),
    Column("code_challenge", Text, nullable=True),
    Column("device_name", Text, nullable=True),
    Column("platform", Text, nullable=True),
    Column("app_version", Text, nullable=True),
    Column("requested_from", Text, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    Column("expires_at", UtcDateTime, nullable=False),
    Column("requested_at", UtcDateTime, nullable=True),
    Column("approved_at", UtcDateTime, nullable=True),
    Column("completed_at", UtcDateTime, nullable=True),
    Column("revoked_at", UtcDateTime, nullable=True),
    Column("session_id", Text, ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True),
    CheckConstraint(
        "status IN ('pending', 'awaiting_approval', 'approved', 'completed', 'revoked')",
        name="status",
    ),
)

#: One uploaded file, and what became of it. The file itself is never stored: an import
#: is somebody's viewing history, and the only copy this server keeps is the titles it
#: managed to identify. The uploaded name is not stored either — it is a string the
#: user's own computer chose, it says nothing the format does not, and it would end up
#: in a console, a log and a backup.
imports = Table(
    "imports",
    metadata,
    Column("id", Text, primary_key=True),
    Column("user_id", Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("source", Text, nullable=False),
    Column("status", Text, nullable=False),
    # What the parser read, what it dropped and why, as JSON. Counts only.
    Column("rows_read", Integer, nullable=False, server_default="0"),
    Column("rows_skipped", Text, nullable=False, server_default="{}"),
    Column("matched", Integer, nullable=False, server_default="0"),
    Column("queued", Integer, nullable=False, server_default="0"),
    # A problem code, never a message from a parser and never a line of the file.
    Column("error_code", Text, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    Column("finished_at", UtcDateTime, nullable=True),
    CheckConstraint("source IN ('netflix', 'imdb', 'letterboxd')", name="source"),
    CheckConstraint("status IN ('running', 'complete', 'failed')", name="status"),
    CheckConstraint("(status = 'failed') = (error_code IS NOT NULL)", name="error_with_status"),
)

#: What a user has watched anywhere but this deck: a file import, a calibration grid
#: tick. Never a vote — the stats and the strategies read ``swipe_votes``, not this —
#: and never the library either, since nothing here is owned (docs/architecture.md).
#: One row per source per title, so a Netflix import and a grid tick about the same film
#: coexist and removing one import leaves the other's answer standing.
watch_history = Table(
    "watch_history",
    metadata,
    Column("user_id", Text, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True),
    Column("source", Text, primary_key=True),
    Column("kind", Text, primary_key=True),
    Column("tmdb_id", Integer, primary_key=True),
    # Which upload wrote this row, so forgetting one import leaves the others standing.
    # Null for a calibration tick, which came from no file. Not part of the key: two
    # imports of the same format that mention the same title are one fact about one
    # household, and the later one owns it.
    Column(
        "import_id", Text, ForeignKey("imports.id", ondelete="SET NULL"), nullable=True, index=True
    ),
    # TMDb's own words about a public film, kept so the batch prompt can name what
    # somebody watched rather than list bare ids.
    Column("title", Text, nullable=False, server_default=""),
    Column("year", Integer, nullable=True),
    Column("seen", Boolean, nullable=False, server_default=true()),
    # The media server port's own EngagementState, or null when the source said only
    # "I have seen this" (a grid tick).
    Column("state", Text, nullable=True),
    Column("progress", Float(), nullable=False, server_default="0"),
    Column("episodes_played", Integer, nullable=True),
    Column("episodes_total", Integer, nullable=True),
    Column("rating", Float(), nullable=True),
    Column("last_watched_at", UtcDateTime, nullable=True),
    Column("created_at", UtcDateTime, nullable=False),
    CheckConstraint("kind IN ('movie', 'tv')", name="kind"),
    CheckConstraint("tmdb_id > 0", name="tmdb_id"),
    CheckConstraint(
        "source IN ('netflix', 'imdb', 'letterboxd', 'grid')",
        name="source",
    ),
    CheckConstraint(
        "state IS NULL OR state IN ('watched', 'mostly_watched', 'in_progress', 'paused', "
        "'abandoned')",
        name="state",
    ),
)

#: The rows an import refused to guess at. ``query`` is the user's own text, kept so
#: they can recognise their own line; ``candidates`` is what TMDb offered, as JSON.
import_reviews = Table(
    "import_reviews",
    metadata,
    Column("id", Text, primary_key=True),
    Column(
        "import_id", Text, ForeignKey("imports.id", ondelete="CASCADE"), nullable=False, index=True
    ),
    Column("user_id", Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("query", Text, nullable=False),
    Column("kind_hint", Text, nullable=True),
    Column("episodes", Integer, nullable=False, server_default="0"),
    Column("rating", Float(), nullable=True),
    Column("last_watched_at", UtcDateTime, nullable=True),
    Column("candidates", Text, nullable=False, server_default="[]"),
    Column("status", Text, nullable=False),
    Column("created_at", UtcDateTime, nullable=False),
    Column("decided_at", UtcDateTime, nullable=True),
    CheckConstraint("kind_hint IS NULL OR kind_hint IN ('movie', 'tv')", name="kind_hint"),
    CheckConstraint("status IN ('pending', 'accepted', 'rejected')", name="status"),
)

#: Sessions of one user, most recent first (the console and the app list them).
Index("ix_sessions_user_id_created_at", sessions.c.user_id, sessions.c.created_at)
#: The caller's imports, most recent first.
Index("ix_imports_user_id_created_at", imports.c.user_id, imports.c.created_at)
